package com.gtu.aiassistant.infrastructure.ai

import java.nio.charset.StandardCharsets
import java.util.Base64
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class AgentArtifactServiceTest {
    @Test
    fun `docx intent is detected as draft-backed artifact`() {
        val intent = ArtifactIntent.fromPrompt("create docx for me with description of GTU")

        assertNotNull(intent)
        assertEquals(ArtifactKind.DOCX, intent.kind)
        assertTrue(intent.needsDraft)
        assertEquals("assistant-document.docx", intent.fileName)
    }

    @Test
    fun `docx renderer uses generated draft instead of raw user command`() {
        val userCommand = "create docx for me with description of GTU"
        val intent = ArtifactIntent.fromPrompt(userCommand) ?: error("Expected docx intent")
        val draft = ArtifactDraft.fromMarkdown(
            markdown = """
                # Georgian Technical University

                Georgian Technical University is a public university in Georgia.

                ## Student Resources
                - Faculties and academic services
                - Public university information
            """.trimIndent(),
            fallbackTitle = "GTU Document"
        )

        val pythonCode = intent.toPythonCode(draft)
        val encodedDraft = Base64.getEncoder().encodeToString(draft.markdown.toByteArray(StandardCharsets.UTF_8))

        assertTrue(pythonCode.contains("base64.b64decode"))
        assertTrue(pythonCode.contains(encodedDraft))
        assertFalse(pythonCode.contains(userCommand))
        assertFalse(pythonCode.contains("Assistant Document"))
        assertFalse(pythonCode.contains("Generated by GTU AI Assistant."))
        assertTrue(pythonCode.contains("output_path.stat().st_size"))
        assertTrue(pythonCode.contains("created artifact: {output_path}"))
    }

    @Test
    fun `chart renderer verifies generated artifact before returning`() {
        val intent = ArtifactIntent.fromPrompt("построй график 1 2 3") ?: error("Expected chart intent")

        val pythonCode = intent.toPythonCode(draft = null)

        assertTrue(pythonCode.contains("plt.savefig(output_path"))
        assertTrue(pythonCode.contains("os.path.getsize(output_path)"))
        assertTrue(pythonCode.contains("created artifact: {output_path}"))
    }
}
